name: First pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: posts-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: |
          cd app
          cp .env.ci .env

      - name: Install Dependencies
        run: |
          cd app
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Generate key
        run: |
          cd app
          php artisan key:generate

      - name: Directory Permissions
        run: |
          cd app
          chmod -R 777 storage bootstrap/cache

      - name: phpstan
        run: |
          cd app
          ./vendor/bin/phpstan analyse --memory-limit=1G app public

      - name: Run tests
        run:  |
          cd app 
          php artisan test
