name: First pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: cp ./.env.ci .env